services:
  wordpress:
    restart: always
    build: .
    links:
      - db:mariadb
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/:/var/www/html/

  db:
    restart: always
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: wordpress

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    links:
      - db:mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  redis:
    restart: always
    image: redis:alpine
    network_mode: "service:wordpress"
    command: ["redis-server", "--appendonly", "yes", "--bind", "127.0.0.1"]
    volumes:
      - ./redis:/data
