services:
  wordpress:
    restart: always
    build: .
    links:
      - db:mariadb
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_CACHE', true);
    volumes:
      - ./wordpress/:/var/www/html/

  db:
    restart: always
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: wordpress

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    links:
      - db:mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/data
